// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package services

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Структура данных для услуги
type Service struct {
	Emoji       string
	Title       string
	Description string
	ColorClass  string
}

// Наши услуги (данные)
var serviceList = []Service{
	{
		Emoji:       "⚡",
		Title:       "Быстрая разработка",
		Description: "Создаем высокопроизводительные приложения на Go. Минимальная задержка, максимальная скорость обработки запросов.",
		ColorClass:  "bg-yellow-100 text-yellow-700",
	},
	{
		Emoji:       "📱",
		Title:       "Мобильная адаптация",
		Description: "Ваш сайт будет идеально выглядеть на любом устройстве: от старого iPhone до широкоформатных мониторов.",
		ColorClass:  "bg-blue-100 text-blue-700",
	},
	{
		Emoji:       "🔒",
		Title:       "Безопасность данных",
		Description: "Внедряем современные протоколы шифрования и защиты. Ваши данные и данные ваших клиентов под надежным замком.",
		ColorClass:  "bg-green-100 text-green-700",
	},
	{
		Emoji:       "☁️",
		Title:       "Облачные решения",
		Description: "Помогаем с миграцией в облако (AWS, Google Cloud, Azure). Настраиваем Docker и Kubernetes для масштабируемости.",
		ColorClass:  "bg-purple-100 text-purple-700",
	},
	{
		Emoji:       "📊",
		Title:       "Аналитика и SEO",
		Description: "Интегрируем инструменты аналитики и оптимизируем структуру сайта для поисковых систем, чтобы вас находили.",
		ColorClass:  "bg-pink-100 text-pink-700",
	},
	{
		Emoji:       "🤝",
		Title:       "Поддержка 24/7",
		Description: "Не бросаем после запуска. Обеспечиваем техническую поддержку, обновления и мониторинг работоспособности.",
		ColorClass:  "bg-indigo-100 text-indigo-700",
	},
}

func Services() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"py-20 bg-gray-50\" id=\"services\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><!-- Заголовок секции --><div class=\"text-center max-w-3xl mx-auto mb-16\"><h2 class=\"text-base font-semibold text-blue-600 tracking-wide uppercase\">Наши возможности</h2><p class=\"mt-2 text-3xl font-extrabold text-gray-900 tracking-tight sm:text-4xl\">Все, что нужно для запуска вашего бизнеса</p><p class=\"mt-4 text-lg text-gray-500\">Мы берем на себя техническую часть, чтобы вы могли сосредоточиться на продукте и продажах.</p></div><!-- Сетка карточек --><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, item := range serviceList {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"bg-white rounded-2xl p-8 border border-gray-100 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300 group\"><!-- Иконка с цветным фоном -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 = []any{"w-12 h-12 rounded-lg flex items-center justify-center text-2xl mb-6 transition-transform group-hover:scale-110 duration-300", item.ColorClass}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/components/home/services/services.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(item.Emoji)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/components/home/services/services.templ`, Line: 72, Col: 19}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div><h3 class=\"text-xl font-bold text-gray-900 mb-3 group-hover:text-blue-600 transition-colors\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(item.Title)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/components/home/services/services.templ`, Line: 76, Col: 19}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</h3><p class=\"text-gray-500 leading-relaxed\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(item.Description)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/components/home/services/services.templ`, Line: 80, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p><!-- Ссылка \"Подробнее\" (декоративная) --><div class=\"mt-6 flex items-center text-blue-600 font-medium text-sm opacity-0 group-hover:opacity-100 transition-opacity duration-300 transform translate-y-2 group-hover:translate-y-0\">Подробнее  <svg class=\"w-4 h-4 ml-1\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 8l4 4m0 0l-4 4m4-4H3\"></path></svg></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
