// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package hero

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "echo_starter/view/components/base"

func Hero() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"relative pt-32 pb-20 lg:pt-40 lg:pb-28 overflow-hidden bg-white\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative\"><div class=\"grid lg:grid-cols-2 gap-12 lg:gap-8 items-center\"><!-- ЛЕВАЯ КОЛОНКА: Текст --><div class=\"max-w-2xl\"><!-- Бейдж (маленькая плашка сверху) --><div class=\"inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-100 text-blue-600 text-xs font-semibold mb-6\"><span class=\"relative flex h-2 w-2\"><span class=\"animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75\"></span> <span class=\"relative inline-flex rounded-full h-2 w-2 bg-blue-500\"></span></span> Версия 2.0 уже доступна</div><h1 class=\"text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 mb-6 leading-tight\">Разрабатывайте на Go <br class=\"hidden lg:block\"><span class=\"text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600\">без лишней боли</span></h1><p class=\"text-lg text-gray-600 mb-8 leading-relaxed\">Полный стартовый набор для создания веб-приложений на Go, Echo, Templ и Tailwind CSS. Скорость компилируемого языка с удобством современной верстки.</p><div class=\"flex flex-col sm:flex-row gap-4\"><!-- Используем наши компоненты кнопок, если они есть, или обычные теги -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = base.ButtonLink("Начать бесплатно", "/signup", base.VariantPrimary).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = base.ButtonLink("Живое демо", "/demo", base.VariantSecondary).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><!-- ПРАВАЯ КОЛОНКА: Визуал --><div class=\"relative lg:ml-auto\"><!-- Декоративное пятно (Glow effect) --><div class=\"absolute -top-10 -right-10 w-72 h-72 bg-blue-400 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob\"></div><div class=\"absolute -bottom-10 -left-10 w-72 h-72 bg-indigo-400 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000\"></div><!-- Карточка-иллюстрация (Имитация интерфейса) --><div class=\"relative bg-white rounded-2xl shadow-2xl border border-gray-200 p-2 transform rotate-2 hover:rotate-0 transition duration-500\"><div class=\"rounded-xl overflow-hidden bg-gray-50 border border-gray-100 aspect-[4/3] flex items-center justify-center relative group\"><!-- Сетка на фоне --><div class=\"absolute inset-0\" style=\"background-image: radial-gradient(#cbd5e1 1px, transparent 1px); background-size: 20px 20px; opacity: 0.5\"></div><!-- Условный контент внутри картинки --><div class=\"text-center z-10\"><div class=\"w-16 h-16 bg-white rounded-2xl shadow-lg mx-auto flex items-center justify-center mb-4 text-3xl\">🚀</div><div class=\"font-bold text-gray-800\">Dashboard</div><div class=\"text-sm text-gray-500\">Analytics & Stats</div></div><!-- Кнопка поверх картинки --><div class=\"absolute bottom-4 right-4 bg-white px-3 py-1.5 rounded-lg shadow-sm text-xs font-bold text-green-600 flex items-center gap-1\"><span class=\"w-2 h-2 rounded-full bg-green-500\"></span> Active</div></div></div></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
